source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'rails', '3.2.11'
#Repository for collecting Locale data for Ruby on Rails I18n as well as other interesting, Rails related I18n stuff http://rails-i18n.org
gem 'rails-i18n', '~> 3.0' # For 3.x
#Rails gem of the Bootstrap based admin theme SB Admin 2. http://dreamingechoes.github.io/boots…
gem 'bootstrap_sb_admin_base_v2'
#Manage Procfile-based applications http://ddollar.github.com/foreman
gem 'foreman'
#Flexible authentication solution for Rails with Warden. http://blog.plataformatec.com.br/tag/…
gem 'devise'
#Translations for the devise gem
gem 'devise-i18n'
#Minimal authorization through OO design and pure Ruby classes
gem "pundit"
#Taint and required checking for Action Pack and enforcement in Active Model
gem 'strong_parameters', '~> 0.2.3'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
#Integration of RubyMoney - Money with Rails
gem 'money-rails', '~>1.12'
#Easy upload management for ActiveRecord
gem 'paperclip', '~> 4.3', '>= 4.3.6'

gem 'sqlite3', '~> 1.3', '< 1.4'

source 'https://rails-assets.org' do
  # Bootstrap
  gem 'rails-assets-bootstrap', '3.3.7'
  #Bootstrap Notify
  gem 'rails-assets-bootstrap.growl'
  #Bootbox JS
  gem 'rails-assets-bootbox'
  #Animate CSS
  gem 'rails-assets-animate-css'
  # Bootstrap Notify
  gem 'rails-assets-bootstrap.growl'
  # BootboxJS
  gem 'rails-assets-bootbox'
  # Animate CSS
  gem 'rails-assets-animate-css'
  # Bootstrap Mardown
  gem 'rails-assets-bootstrap-markdown'
  # Marked
  gem 'rails-assets-marked'

end


#Better error page for Rack apps
group :development do
  gem "better_errors"
  gem "binding_of_caller"
  #Rails >= 3 pry initializer
  gem 'pry-rails'
  #Rails console enhancement - Make Your Rails Console Awesome https://rubygems.org/gems/awesome_rai…
  gem 'awesome_rails_console'
  #Rails ERD runs on all Rails 3+ platforms: Ruby 1.8/1.9, Rubinius, or JRuby all work fine. Add Rails ERD as a plugin to your Ruby on Rails application. In your Gemfile...
  gem "rails-erd"
  #A library for generating fake data such as names, addresses, and phone numbers.
  gem 'faker'
  #O Lero-lero Generator é uma ferramenta capaz de gerar frases que 'falam' muita coisa mas que não tem conteúdo algum.
  gem 'lerolero_generator'
  #MailCatcher
  gem 'mailcatcher'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
